version: '3.4'

services:
  apigateway:
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    command:
      # only in debug
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # default
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.insecure.address=:80"
      - "--entrypoints.websecure.address=:443"
      # for HTTPS
      - "--certificatesresolvers.le.acme.email=alma@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    labels:
      # HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"      
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=insecure"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https" 

  schemes:
    image: schemes:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #; https://+:443
    ports:
      - 5082:80

  upload:
    image: upload:dev
    ports:
      - "5083:80"

  web:
    image: web:dev
    ports:
      - "5084:80"

  mongodb:
    ports:
      - "27017:27017"


