version: '3.4'

services:
  apigateway:
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    command:
      # only in debug
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # default
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.insecure.address=:80"
      - "--entrypoints.websecure.address=:443"

  schemes:
    image: schemes:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #; https://+:443
    ports:
      - 5082:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.schemes.rule=PathPrefix(`/api/schemes`)

  upload:
    image: upload:dev
    ports:
      - "5083:80"

  web:
    image: web:dev
    ports:
      - "5084:80"

  mongodb:
    ports:
      - "27017:27017"


