version: '3.4'

services:
  apigateway:
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    command:
      # only in debug
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

  schemes:
    image: schemes:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
    ports:
      - 5082:80

  upload:
    image: upload:dev
    ports:
      - "5083:80"

  web:
    image: web:dev
    ports:
      - "5084:80"

  mongodb:
    ports:
      - "27017:27017"


