version: '3.4'

services:
  apigateway:
    image: traefik:v2.2.1
    ports:
      - "5080:80" # Port of the API Gateway, which will be the port behind which the system will be published
      - "5088:8080" # Dashboard of Traefik for troubleshooting
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - meteor-network

  schemes:
    image: ${DOCKER_REGISTRY-}schemes
    build:
      context: ..
      dockerfile: Schemes/Schemes.Api/Dockerfile
    networks:
      - meteor-network

  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: alma
    networks:
      - meteor-network
    volumes:
      - meteor-sql-data:/var/lib/mysql

  mongodb:
    image: mongo:4.2.8
    networks:
      - meteor-network
    volumes:
      - meteor-mongo-data:/data/db

  redis:
    image: redis:6.0.9-alpine
    networks:
      - meteor-network

volumes:
  meteor-sql-data:
    driver: local
  meteor-mongo-data:
    driver: local

networks:
  meteor-network:
    driver: bridge